### ISSUE TITLE
No need to use `CMAKE_VS_PLATFORM_NAME` in MinGW build

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#10]
We currently use `${CMAKE_VS_PLATFORM_NAME}` to create the package name in MinGW:
https://github.com/clementperon/PcapPlusPlus/blob/4e9d898d82254be92b4e8e693fc0adfc64e4c842/CMakeLists.txt#L346

Since it's not VS, the resolved name is empty and the package name is:
`PcapPlusPlus-22.11+-mingw64-gcc--12.2.0.zip `
(with `--`)

**Comment by clementperon** [comment]
done
