### ISSUE TITLE
`README.release.md` has `.html` extension in macOS builds

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#12]
In macOS builds the file name is `README.html`:

![image](https://github.com/PcapPlusPlus/new-packaging/assets/9059541/55047902-b2aa-4192-965a-afe1bd95a1e5)

**Comment by clementperon** [comment]
Apple productbuild cannot handle .md or file without extension Use textutil to convert them to HTML

I will keep the .md for the moment in the TGZ

**Comment by clementperon** [comment]
Fixed by https://github.com/clementperon/PcapPlusPlus/commit/8b064ac6202450b2449822a31685d4f577e4c4f1
