### ISSUE TITLE
`README.release.md` doesn't contain the information in `/cmake/package/READMEs`

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#2]
Currently it just contains the release notes and version number, but not the info in:
https://github.com/clementperon/PcapPlusPlus/tree/package/cmake/package/READMEs

**Comment by clementperon** [comment]
It should which one doesn't work ? 

 ```
 # Generate output README
  file(READ "${_PCAPPP_PACKAGE_README_PATH}/README.release.header" _CONTENT)
  file(APPEND ${_PCAPPP_PACKAGE_README_OUTFILE} "${_CONTENT}")

  if(_PCAPPP_PACKAGE_README_CUSTOM_PATH)
    file(READ ${_PCAPPP_PACKAGE_README_CUSTOM_PATH} _CONTENT)
    file(APPEND ${_PCAPPP_PACKAGE_README_OUTFILE} "${_CONTENT}")
  endif()

  file(READ "${_PCAPPP_PACKAGE_README_PATH}/release_notes.txt" _CONTENT)
  file(APPEND ${_PCAPPP_PACKAGE_README_OUTFILE} "${_CONTENT}")`
  ```

**Comment by seladb** [comment]
I think it happens in all Linux builds, for example:
https://github.com/clementperon/PcapPlusPlus/releases/download/99.29.2/pcapplusplus-22.11+-ubuntu-22.04-gcc-11.2.0-x86_64.tar.gz

**Comment by clementperon** [comment]
fixed by https://github.com/clementperon/PcapPlusPlus/commit/65cfca689d920a3f5b188fb271f41b6d150ba711
