### ISSUE TITLE
MacOS - missing libs in `PcapPlusPlus.pc`

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#21]
In order to use pkg-config on macOS we need to add 2 params to `Libs`: `-framework SystemConfiguration -framework CoreFoundation`

Like this:
```text
# PcapPlusPlus.pc

...

Libs: `-framework SystemConfiguration -framework CoreFoundation -L${libdir} -lPcap++ -lPacket++ -lCommon++
```

Like we used to do before: https://github.com/seladb/PcapPlusPlus/blob/f86297140ed392ca69d45993fcc13d958a6cd5da/mk/PcapPlusPlus.mk.macosx#L7

**Comment by clementperon** [comment]
should be fixed https://github.com/clementperon/PcapPlusPlus/commit/622fde71e2a141e483f25d5b04f23976864a5134
