### ISSUE TITLE
Example app name is `Tutorial-HelloWorld` instead of `example-app`

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#3]
```
drwxrwxr-x 3 seladb seladb    4096 Jun  7 07:28 ./
drwxrwxr-x 6 seladb seladb    4096 Jun  7 07:12 ../
-rw-r--r-- 1 seladb seladb     447 Aug 20  2021 1_packet.pcap
drwxrwxr-x 3 seladb seladb    4096 Jun  7 07:14 build/
-rw-r--r-- 1 seladb seladb     918 Mar 17 06:10 CMakeLists.txt
-rw-r--r-- 1 seladb seladb    1111 Sep 27  2021 main.cpp
-rw-r--r-- 1 seladb seladb     367 Feb  1 07:15 README.md
-rwxrwxr-x 1 seladb seladb 1256712 Jun  7 07:14 Tutorial-HelloWorld*
```

**Comment by clementperon** [comment]
This is a simple copy of the Examples/Tutorials/Tutorial-HelloWorld.

Can we create a new "Example-App"? in "Examples/ExampleApp" ? that is dedicated to release?

**Comment by seladb** [comment]
Yes, adding an `ExampleApp` can be a good idea! It can contain what we have in `Tutorial-HelloWorld` (and maybe more if you can think of something that is simple enough to add)

**Comment by clementperon** [comment]
Added an ExampleApp and Package will install it:
https://github.com/clementperon/PcapPlusPlus/commit/fcf6bd342c25b88013c007e0c1ef68ff47be112c 
https://github.com/clementperon/PcapPlusPlus/commit/cc7f7c23ebd32b95c1c7bf1193c10a9c0eda2c41
