### ISSUE TITLE
What is the right way to install a downloaded package?

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#6]
Let's say I'm downloading a package, for example https://github.com/clementperon/PcapPlusPlus/releases/download/99.28.1/PcapPlusPlus-22.11+-ubuntu-22.04-gcc-11.2.0-x86_64.tar.gz

How do I get it installed?

It probably varies per platform, we need specific instructions...

**Comment by clementperon** [comment]
.tar.gz should be installed by extracting to /usr/local but an archive is not an installer so it will not magically install by itself.

We can introduce .deb / .rpm / .pkg for Debian Family/ Red Hat or MacOS

**Comment by seladb** [comment]
We should probably document in in the README files like I mentioned here: https://github.com/PcapPlusPlus/new-packaging/issues/4#issuecomment-1585845373

Do we also want to introduce `.deb', `.rpm` and `.pkg` in the coming release? We can also do it in a subsequent PR right after we merge this one

**Comment by clementperon** [comment]
I would prefer to introduce .deb .rm and .pkg in another PR this one is already big

**Comment by seladb** [comment]
We can close this issue for now. We can discuss rpm, deb and pkg separately as you suggested
