### ISSUE TITLE
Android - create just one package instead of 4 (one per arch)

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#8]

**Comment by clementperon** [comment]
We can but it should be done by the github CI not by CMake. Or we should introduce have a CMake script that build 4 releases and then compress into one

It not sure why do you want a specific case for Android?

**Comment by seladb** [comment]
Actually you're right, we can keep them separate I guess

**Comment by clementperon** [comment]
Issue can be closed ?

**Comment by seladb** [comment]
@clementperon by default Android Studio tries to build for all platforms, so it expects folders for all of them under `<APP_ROOT_FOLDER>/app/libs/pcapplusplus`. I think that's the reason the [existing package](https://github.com/seladb/PcapPlusPlus/releases/download/v22.11/pcapplusplus-22.11-android.tar.gz) has all 4 archs
