### ISSUE TITLE
Visual Studio packages should have VS version

### ISSUE THREAD

**Issue by seladb** [PcapPlusPlus/new-packaging#9]
They currently contain some weird number, maybe the compiler version? `19.29.30148`.

The name should be either:
`PcapPlusPlus-22.11+-windows-msvc-Win32-vs2019.zip `
`PcapPlusPlus-22.11+-windows-msvc-Win32-vs2022.zip `

**Comment by clementperon** [comment]
It's the VS version https://reactos.org/wiki/Visual_Studio_Versions

**Comment by clementperon** [comment]
Done with https://github.com/clementperon/PcapPlusPlus/commit/a5e0737abd86077ec160e740becea278449b8bfe

I have change the Cmake indentation else it was not really readable
